import importlib.util
import sqlite3
import unittest
from pathlib import Path


SCRIPT = Path(__file__).resolve().parents[1] / "migrate_to_postgres.py"


def load_module():
    spec = importlib.util.spec_from_file_location("migrate_to_postgres", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def make_sqlite_db(path: Path) -> None:
    conn = sqlite3.connect(path)
    conn.executescript(
        """
        CREATE TABLE authors (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT UNIQUE NOT NULL,
            is_wrestler INTEGER DEFAULT 0,
            notes TEXT
        );
        CREATE TABLE books (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE book_authors (
            book_id INTEGER NOT NULL,
            author_id INTEGER NOT NULL,
            role TEXT DEFAULT 'author',
            PRIMARY KEY (book_id, author_id, role)
        );
        CREATE VIEW author_names AS SELECT id, name FROM authors;
        INSERT INTO authors (name, is_wrestler, notes)
        VALUES ('Lansdowne Test', 1, 'uses ''quotes'' and tabs');
        INSERT INTO books (title) VALUES ('Territory Book');
        INSERT INTO book_authors (book_id, author_id, role) VALUES (1, 1, 'author');
        """
    )
    conn.close()


class MigrationSqlTests(unittest.TestCase):
    def test_render_postgres_sql_exports_schema_data_and_sequences(self):
        import tempfile

        module = load_module()
        with tempfile.TemporaryDirectory() as tmp:
            sqlite_path = Path(tmp) / "source.db"
            make_sqlite_db(sqlite_path)

            sql = module.render_postgres_sql(sqlite_path)

        self.assertIn("CREATE TABLE authors", sql)
        self.assertIn("id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
        self.assertIn("book_id INTEGER NOT NULL", sql)
        self.assertIn("PRIMARY KEY (book_id, author_id, role)", sql)
        self.assertNotIn("book_id INTEGER GENERATED BY DEFAULT AS IDENTITY", sql)
        self.assertIn("COPY authors", sql)
        self.assertIn("Lansdowne Test\t1\tuses 'quotes' and tabs", sql)
        self.assertIn("CREATE VIEW author_names AS SELECT id, name FROM authors", sql)
        self.assertIn("setval(pg_get_serial_sequence('authors', 'id'), 1, true)", sql)

    def test_empty_identity_table_sequence_starts_at_one(self):
        import tempfile

        module = load_module()
        with tempfile.TemporaryDirectory() as tmp:
            sqlite_path = Path(tmp) / "source.db"
            conn = sqlite3.connect(sqlite_path)
            conn.execute(
                "CREATE TABLE empty_items (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)"
            )
            conn.close()

            sql = module.render_postgres_sql(sqlite_path)

        self.assertIn("setval(pg_get_serial_sequence('empty_items', 'id'), 1, false)", sql)

    def test_sqlite_table_counts_excludes_internal_tables(self):
        import tempfile

        module = load_module()
        with tempfile.TemporaryDirectory() as tmp:
            sqlite_path = Path(tmp) / "source.db"
            make_sqlite_db(sqlite_path)

            self.assertEqual(
                module.sqlite_table_counts(sqlite_path),
                {"authors": 1, "book_authors": 1, "books": 1},
            )


if __name__ == "__main__":
    unittest.main()
