CREATE TABLE "authors" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "authors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"ring_name" text,
	"is_wrestler" integer DEFAULT 0,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "book_authors" (
	"book_id" integer NOT NULL,
	"author_id" integer NOT NULL,
	"role" text DEFAULT 'author' NOT NULL,
	CONSTRAINT "book_authors_pkey" PRIMARY KEY("book_id","author_id","role")
);
--> statement-breakpoint
CREATE TABLE "books" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "books_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"subtitle" text,
	"category_code" text NOT NULL,
	"publisher" text,
	"year_published" integer,
	"isbn10" text,
	"isbn13" text,
	"pages" integer,
	"format" text,
	"language" text DEFAULT 'English',
	"country" text,
	"subject_wrestler" text,
	"era" text,
	"territory_or_promotion" text,
	"synopsis" text,
	"source_url" text,
	"confidence" text DEFAULT 'medium',
	"primary_source_value" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"label" text NOT NULL,
	"description" text,
	CONSTRAINT "categories_code_key" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "faction_members" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "faction_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"faction_id" integer NOT NULL,
	"wrestler_id" integer NOT NULL,
	"role" text,
	"joined_year" integer,
	"left_year" integer,
	"notes" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "factions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "factions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"type" text NOT NULL,
	"formed_year" integer,
	"disbanded_year" integer,
	"primary_territory_id" integer,
	"notes" text,
	"confidence" text DEFAULT 'medium',
	"source_url" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "issue_cover_subjects" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "issue_cover_subjects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"issue_id" integer NOT NULL,
	"wrestler_id" integer,
	"faction_id" integer,
	"subject_name" text,
	"position" text,
	"notes" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "pending_wrestlers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pending_wrestlers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"profightdb_id" integer,
	"profightdb_slug" text,
	"printed_name" text NOT NULL,
	"normalized_name" text NOT NULL,
	"other_printed_names" text,
	"first_seen_date" text,
	"last_seen_date" text,
	"occurrence_count" integer DEFAULT 1 NOT NULL,
	"resolved_wrestler_id" integer,
	"notes" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "periodical_issues" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "periodical_issues_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"periodical_id" integer NOT NULL,
	"publication_date" text NOT NULL,
	"period_date" text,
	"issue_number" text,
	"volume" integer,
	"cover_image_url" text,
	"cover_description" text,
	"cover_story" text,
	"profightdb_id" integer,
	"drive_pdf_path" text,
	"in_collection" integer DEFAULT 0,
	"source_url" text,
	"confidence" text DEFAULT 'medium',
	"notes" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "periodicals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "periodicals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"publisher" text,
	"country" text,
	"language" text DEFAULT 'English',
	"year_started" integer,
	"year_ended" integer,
	"frequency" text,
	"type" text,
	"parent_company" text,
	"notes" text,
	"issue_count_known" integer,
	"archive_in_collection" integer DEFAULT 0,
	"source_url" text,
	"confidence" text DEFAULT 'medium',
	"created_at" text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "ranking_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ranking_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ranking_list_id" integer NOT NULL,
	"rank" integer NOT NULL,
	"wrestler_id" integer,
	"faction_id" integer,
	"entry_name" text NOT NULL,
	"previous_rank" integer,
	"notes" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP,
	"pending_wrestler_id" integer
);
--> statement-breakpoint
CREATE TABLE "ranking_lists" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ranking_lists_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"issue_id" integer NOT NULL,
	"list_label" text NOT NULL,
	"list_scope" text NOT NULL,
	"territory_id" integer,
	"list_size" integer,
	"source_url" text,
	"notes" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "reign_participants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reign_participants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"reign_id" integer NOT NULL,
	"wrestler_id" integer NOT NULL,
	"position" integer NOT NULL,
	"ring_name_used" text,
	CONSTRAINT "reign_participants_reign_id_wrestler_id_key" UNIQUE("reign_id","wrestler_id"),
	CONSTRAINT "reign_participants_reign_id_position_key" UNIQUE("reign_id","position")
);
--> statement-breakpoint
CREATE TABLE "reigns" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reigns_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title_id" integer NOT NULL,
	"wrestler_id" integer,
	"is_vacancy" boolean DEFAULT false NOT NULL,
	"sequence_order" integer NOT NULL,
	"reign_number" integer,
	"reign_number_for_wrestler" integer,
	"start_date" text,
	"end_date" text,
	"start_date_precision" text,
	"end_date_precision" text,
	"duration_days" integer,
	"won_in_city" text,
	"won_in_state" text,
	"won_in_country" text,
	"source_url" text,
	"notes" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP,
	"team_name" text,
	CONSTRAINT "reigns_title_id_sequence_order_key" UNIQUE("title_id","sequence_order"),
	CONSTRAINT "reigns_check" CHECK ((is_vacancy = false) OR (wrestler_id IS NULL))
);
--> statement-breakpoint
CREATE TABLE "research_sources" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "research_sources_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"url" text NOT NULL,
	"description" text,
	"consulted_at" text DEFAULT CURRENT_TIMESTAMP,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "territories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "territories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"short_name" text,
	"region" text,
	"nwa_member" integer DEFAULT 0,
	"headquarters_city" text,
	"headquarters_state" text,
	"year_founded" integer,
	"year_closed" integer,
	"promoter_lineage" text,
	"notes" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP,
	"cagematch_id" text,
	"country" text,
	"aliases" text,
	"cagematch_url" text GENERATED ALWAYS AS (
CASE
    WHEN ((cagematch_id IS NOT NULL) AND (cagematch_id <> ''::text)) THEN ('https://www.cagematch.net/?id=8&nr='::text || cagematch_id)
    ELSE NULL::text
END) STORED
);
--> statement-breakpoint
CREATE TABLE "title_aliases" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "title_aliases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title_id" integer NOT NULL,
	"name" text NOT NULL,
	"effective_from" text,
	"effective_to" text,
	"notes" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "title_aliases_title_id_name_effective_from_key" UNIQUE("title_id","name","effective_from")
);
--> statement-breakpoint
CREATE TABLE "titles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "titles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"status" text,
	"title_type" text,
	"weight_class" text,
	"territory_id" integer,
	"promotion_name" text,
	"inception_date" text,
	"retired_date" text,
	"cagematch_id" text,
	"cagematch_url" text GENERATED ALWAYS AS (
CASE
    WHEN ((cagematch_id IS NOT NULL) AND (cagematch_id <> ''::text)) THEN ('https://www.cagematch.net/?id=5&nr='::text || cagematch_id)
    ELSE NULL::text
END) STORED,
	"notes" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "titles_cagematch_id_key" UNIQUE("cagematch_id")
);
--> statement-breakpoint
CREATE TABLE "wrestler_territory_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wrestler_territory_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"wrestler_id" integer NOT NULL,
	"territory_id" integer NOT NULL,
	"start_year" integer,
	"start_month" integer,
	"end_year" integer,
	"end_month" integer,
	"role_during_run" text,
	"ring_name_during_run" text,
	"primary_run" integer DEFAULT 0,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "wrestlers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wrestlers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"legal_name" text,
	"primary_ring_name" text NOT NULL,
	"other_ring_names" text,
	"born_date" text,
	"died_date" text,
	"living" integer,
	"debut_year" integer,
	"retired_year" integer,
	"primary_role" text,
	"hometown_billed" text,
	"hometown_real" text,
	"finisher" text,
	"style" text,
	"socials" text,
	"convention_status" text,
	"last_known_appearance" text,
	"footage_notes" text,
	"midcard_files_status" text,
	"midcard_files_priority" integer,
	"why_they_mattered" text,
	"notes" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP,
	"cagematch_id" text,
	"cagematch_url" text GENERATED ALWAYS AS (
CASE
    WHEN ((cagematch_id IS NOT NULL) AND (cagematch_id <> ''::text)) THEN ('https://www.cagematch.net/?id=2&nr='::text || cagematch_id)
    ELSE NULL::text
END) STORED
);
--> statement-breakpoint
ALTER TABLE "book_authors" ADD CONSTRAINT "book_authors_fk_0" FOREIGN KEY ("author_id") REFERENCES "public"."authors"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "book_authors" ADD CONSTRAINT "book_authors_fk_1" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "books" ADD CONSTRAINT "books_fk_0" FOREIGN KEY ("category_code") REFERENCES "public"."categories"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "faction_members" ADD CONSTRAINT "faction_members_fk_0" FOREIGN KEY ("wrestler_id") REFERENCES "public"."wrestlers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "faction_members" ADD CONSTRAINT "faction_members_fk_1" FOREIGN KEY ("faction_id") REFERENCES "public"."factions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "factions" ADD CONSTRAINT "factions_fk_0" FOREIGN KEY ("primary_territory_id") REFERENCES "public"."territories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue_cover_subjects" ADD CONSTRAINT "issue_cover_subjects_fk_0" FOREIGN KEY ("faction_id") REFERENCES "public"."factions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue_cover_subjects" ADD CONSTRAINT "issue_cover_subjects_fk_1" FOREIGN KEY ("wrestler_id") REFERENCES "public"."wrestlers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue_cover_subjects" ADD CONSTRAINT "issue_cover_subjects_fk_2" FOREIGN KEY ("issue_id") REFERENCES "public"."periodical_issues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pending_wrestlers" ADD CONSTRAINT "pending_wrestlers_fk_0" FOREIGN KEY ("resolved_wrestler_id") REFERENCES "public"."wrestlers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "periodical_issues" ADD CONSTRAINT "periodical_issues_fk_0" FOREIGN KEY ("periodical_id") REFERENCES "public"."periodicals"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ranking_entries" ADD CONSTRAINT "ranking_entries_fk_0" FOREIGN KEY ("pending_wrestler_id") REFERENCES "public"."pending_wrestlers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ranking_entries" ADD CONSTRAINT "ranking_entries_fk_1" FOREIGN KEY ("faction_id") REFERENCES "public"."factions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ranking_entries" ADD CONSTRAINT "ranking_entries_fk_2" FOREIGN KEY ("wrestler_id") REFERENCES "public"."wrestlers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ranking_entries" ADD CONSTRAINT "ranking_entries_fk_3" FOREIGN KEY ("ranking_list_id") REFERENCES "public"."ranking_lists"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ranking_lists" ADD CONSTRAINT "ranking_lists_fk_0" FOREIGN KEY ("territory_id") REFERENCES "public"."territories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ranking_lists" ADD CONSTRAINT "ranking_lists_fk_1" FOREIGN KEY ("issue_id") REFERENCES "public"."periodical_issues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reign_participants" ADD CONSTRAINT "reign_participants_reign_id_fkey" FOREIGN KEY ("reign_id") REFERENCES "public"."reigns"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reign_participants" ADD CONSTRAINT "reign_participants_wrestler_id_fkey" FOREIGN KEY ("wrestler_id") REFERENCES "public"."wrestlers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reigns" ADD CONSTRAINT "reigns_title_id_fkey" FOREIGN KEY ("title_id") REFERENCES "public"."titles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reigns" ADD CONSTRAINT "reigns_wrestler_id_fkey" FOREIGN KEY ("wrestler_id") REFERENCES "public"."wrestlers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "title_aliases" ADD CONSTRAINT "title_aliases_title_id_fkey" FOREIGN KEY ("title_id") REFERENCES "public"."titles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "titles" ADD CONSTRAINT "titles_territory_id_fkey" FOREIGN KEY ("territory_id") REFERENCES "public"."territories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wrestler_territory_runs" ADD CONSTRAINT "wrestler_territory_runs_fk_0" FOREIGN KEY ("territory_id") REFERENCES "public"."territories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wrestler_territory_runs" ADD CONSTRAINT "wrestler_territory_runs_fk_1" FOREIGN KEY ("wrestler_id") REFERENCES "public"."wrestlers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "authors_name_key" ON "authors" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "book_authors_book_id_author_id_role_key" ON "book_authors" USING btree ("book_id","author_id","role");--> statement-breakpoint
CREATE UNIQUE INDEX "books_title_year_published_isbn13_key" ON "books" USING btree ("title","year_published","isbn13");--> statement-breakpoint
CREATE INDEX "idx_books_category" ON "books" USING btree ("category_code");--> statement-breakpoint
CREATE INDEX "idx_books_country" ON "books" USING btree ("country");--> statement-breakpoint
CREATE INDEX "idx_books_subject" ON "books" USING btree ("subject_wrestler");--> statement-breakpoint
CREATE INDEX "idx_books_year" ON "books" USING btree ("year_published");--> statement-breakpoint
CREATE UNIQUE INDEX "faction_members_faction_id_wrestler_id_joined_year_key" ON "faction_members" USING btree ("faction_id","wrestler_id","joined_year");--> statement-breakpoint
CREATE INDEX "idx_faction_members_faction" ON "faction_members" USING btree ("faction_id");--> statement-breakpoint
CREATE INDEX "idx_faction_members_wrestler" ON "faction_members" USING btree ("wrestler_id");--> statement-breakpoint
CREATE UNIQUE INDEX "factions_name_formed_year_key" ON "factions" USING btree ("name","formed_year");--> statement-breakpoint
CREATE INDEX "idx_factions_name" ON "factions" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_factions_type" ON "factions" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_cover_subjects_faction" ON "issue_cover_subjects" USING btree ("faction_id");--> statement-breakpoint
CREATE INDEX "idx_cover_subjects_issue" ON "issue_cover_subjects" USING btree ("issue_id");--> statement-breakpoint
CREATE INDEX "idx_cover_subjects_wrestler" ON "issue_cover_subjects" USING btree ("wrestler_id");--> statement-breakpoint
CREATE INDEX "idx_pending_wrestlers_count" ON "pending_wrestlers" USING btree ("occurrence_count");--> statement-breakpoint
CREATE INDEX "idx_pending_wrestlers_pfdb" ON "pending_wrestlers" USING btree ("profightdb_id");--> statement-breakpoint
CREATE INDEX "idx_pending_wrestlers_resolved" ON "pending_wrestlers" USING btree ("resolved_wrestler_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pending_wrestlers_normalized_name_key" ON "pending_wrestlers" USING btree ("normalized_name");--> statement-breakpoint
CREATE UNIQUE INDEX "pending_wrestlers_profightdb_id_key" ON "pending_wrestlers" USING btree ("profightdb_id");--> statement-breakpoint
CREATE INDEX "idx_issues_periodical_date" ON "periodical_issues" USING btree ("periodical_id","publication_date");--> statement-breakpoint
CREATE INDEX "idx_issues_profightdb" ON "periodical_issues" USING btree ("profightdb_id");--> statement-breakpoint
CREATE UNIQUE INDEX "periodical_issues_periodical_id_profightdb_id_key" ON "periodical_issues" USING btree ("periodical_id","profightdb_id");--> statement-breakpoint
CREATE UNIQUE INDEX "periodical_issues_periodical_id_publication_date_key" ON "periodical_issues" USING btree ("periodical_id","publication_date");--> statement-breakpoint
CREATE INDEX "idx_periodicals_country" ON "periodicals" USING btree ("country");--> statement-breakpoint
CREATE UNIQUE INDEX "periodicals_title_year_started_key" ON "periodicals" USING btree ("title","year_started");--> statement-breakpoint
CREATE INDEX "idx_ranking_entries_faction" ON "ranking_entries" USING btree ("faction_id");--> statement-breakpoint
CREATE INDEX "idx_ranking_entries_list" ON "ranking_entries" USING btree ("ranking_list_id");--> statement-breakpoint
CREATE INDEX "idx_ranking_entries_name" ON "ranking_entries" USING btree ("entry_name");--> statement-breakpoint
CREATE INDEX "idx_ranking_entries_pending" ON "ranking_entries" USING btree ("pending_wrestler_id");--> statement-breakpoint
CREATE INDEX "idx_ranking_entries_wrestler" ON "ranking_entries" USING btree ("wrestler_id");--> statement-breakpoint
CREATE UNIQUE INDEX "ranking_entries_ranking_list_id_rank_key" ON "ranking_entries" USING btree ("ranking_list_id","rank");--> statement-breakpoint
CREATE INDEX "idx_ranking_lists_issue" ON "ranking_lists" USING btree ("issue_id");--> statement-breakpoint
CREATE INDEX "idx_ranking_lists_scope" ON "ranking_lists" USING btree ("list_scope");--> statement-breakpoint
CREATE INDEX "idx_ranking_lists_territory" ON "ranking_lists" USING btree ("territory_id");--> statement-breakpoint
CREATE UNIQUE INDEX "ranking_lists_issue_id_list_label_key" ON "ranking_lists" USING btree ("issue_id","list_label");--> statement-breakpoint
CREATE INDEX "idx_reign_participants_reign" ON "reign_participants" USING btree ("reign_id");--> statement-breakpoint
CREATE INDEX "idx_reign_participants_wrestler" ON "reign_participants" USING btree ("wrestler_id");--> statement-breakpoint
CREATE INDEX "idx_reigns_start" ON "reigns" USING btree ("start_date");--> statement-breakpoint
CREATE INDEX "idx_reigns_title" ON "reigns" USING btree ("title_id");--> statement-breakpoint
CREATE INDEX "idx_reigns_vacancy" ON "reigns" USING btree ("is_vacancy");--> statement-breakpoint
CREATE INDEX "idx_reigns_wrestler" ON "reigns" USING btree ("wrestler_id");--> statement-breakpoint
CREATE UNIQUE INDEX "research_sources_url_key" ON "research_sources" USING btree ("url");--> statement-breakpoint
CREATE INDEX "idx_territories_cm" ON "territories" USING btree ("cagematch_id");--> statement-breakpoint
CREATE INDEX "idx_territories_country" ON "territories" USING btree ("country");--> statement-breakpoint
CREATE INDEX "idx_territories_region" ON "territories" USING btree ("region");--> statement-breakpoint
CREATE UNIQUE INDEX "territories_name_key" ON "territories" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_title_aliases_title" ON "title_aliases" USING btree ("title_id");--> statement-breakpoint
CREATE INDEX "idx_titles_cm" ON "titles" USING btree ("cagematch_id");--> statement-breakpoint
CREATE INDEX "idx_titles_status" ON "titles" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_titles_territory" ON "titles" USING btree ("territory_id");--> statement-breakpoint
CREATE INDEX "idx_wt_runs_territory" ON "wrestler_territory_runs" USING btree ("territory_id");--> statement-breakpoint
CREATE INDEX "idx_wt_runs_wrestler" ON "wrestler_territory_runs" USING btree ("wrestler_id");--> statement-breakpoint
CREATE INDEX "idx_wrestlers_cm" ON "wrestlers" USING btree ("cagematch_id");--> statement-breakpoint
CREATE INDEX "idx_wrestlers_living" ON "wrestlers" USING btree ("living");--> statement-breakpoint
CREATE INDEX "idx_wrestlers_midcard" ON "wrestlers" USING btree ("midcard_files_status");--> statement-breakpoint
CREATE VIEW "public"."v_current_champions" AS (SELECT DISTINCT ON (r.title_id) t.id AS title_id, t.name AS title_name, t.status AS title_status, r.id AS reign_id, r.wrestler_id, w.primary_ring_name AS wrestler_name, r.team_name, COALESCE(r.team_name, ( SELECT string_agg(w2.primary_ring_name, ' & '::text ORDER BY rp."position") AS string_agg FROM reign_participants rp JOIN wrestlers w2 ON w2.id = rp.wrestler_id WHERE rp.reign_id = r.id), w.primary_ring_name) AS holder_display, r.reign_number, r.reign_number_for_wrestler, r.start_date, r.end_date, r.duration_days, r.won_in_city, r.won_in_state, r.won_in_country FROM titles t LEFT JOIN reigns r ON r.title_id = t.id AND r.is_vacancy = false LEFT JOIN wrestlers w ON w.id = r.wrestler_id ORDER BY r.title_id, r.sequence_order DESC);--> statement-breakpoint
CREATE VIEW "public"."v_issue_browser" AS (SELECT pi.id, p.title AS periodical, pi.publication_date, pi.period_date, pi.issue_number, pi.cover_image_url, pi.cover_description, pi.drive_pdf_path, ( SELECT count(*) AS count FROM ranking_lists WHERE ranking_lists.issue_id = pi.id) AS list_count, ( SELECT string_agg(COALESCE(w.primary_ring_name, ics.subject_name), ', '::text) AS string_agg FROM issue_cover_subjects ics LEFT JOIN wrestlers w ON ics.wrestler_id = w.id WHERE ics.issue_id = pi.id) AS cover_subjects FROM periodical_issues pi JOIN periodicals p ON pi.periodical_id = p.id);--> statement-breakpoint
CREATE VIEW "public"."v_longest_reigns" AS (SELECT r.id AS reign_id, t.name AS title_name, COALESCE(r.team_name, ( SELECT string_agg(w2.primary_ring_name, ' & '::text ORDER BY rp."position") AS string_agg FROM reign_participants rp JOIN wrestlers w2 ON w2.id = rp.wrestler_id WHERE rp.reign_id = r.id), w.primary_ring_name) AS holder_display, r.team_name, r.reign_number, r.reign_number_for_wrestler, r.start_date, r.end_date, r.duration_days FROM reigns r JOIN titles t ON t.id = r.title_id LEFT JOIN wrestlers w ON w.id = r.wrestler_id WHERE r.is_vacancy = false AND r.duration_days IS NOT NULL ORDER BY r.duration_days DESC);--> statement-breakpoint
CREATE VIEW "public"."v_pending_wrestlers_queue" AS (SELECT pw.id, pw.profightdb_id, pw.profightdb_slug, pw.printed_name, pw.other_printed_names, pw.occurrence_count, pw.first_seen_date, pw.last_seen_date, pw.resolved_wrestler_id, w.primary_ring_name AS resolved_name, CASE WHEN pw.resolved_wrestler_id IS NOT NULL THEN 1 ELSE 0 END AS merged FROM pending_wrestlers pw LEFT JOIN wrestlers w ON pw.resolved_wrestler_id = w.id);--> statement-breakpoint
CREATE VIEW "public"."v_ranking_history" AS (SELECT w.id AS wrestler_id, w.primary_ring_name, p.title AS periodical, pi.publication_date, pi.period_date, pi.issue_number, rl.list_label, rl.list_scope, re.rank, re.previous_rank, re.entry_name AS as_printed FROM ranking_entries re JOIN ranking_lists rl ON re.ranking_list_id = rl.id JOIN periodical_issues pi ON rl.issue_id = pi.id JOIN periodicals p ON pi.periodical_id = p.id LEFT JOIN wrestlers w ON re.wrestler_id = w.id);--> statement-breakpoint
CREATE VIEW "public"."v_reigns_full" AS (SELECT r.id AS reign_id, r.title_id, t.name AS title_name, t.cagematch_id AS title_cagematch_id, r.wrestler_id, w.primary_ring_name AS wrestler_name, w.cagematch_id AS wrestler_cagematch_id, r.team_name, COALESCE( CASE WHEN r.is_vacancy THEN 'VACANT'::text ELSE NULL::text END, r.team_name, ( SELECT string_agg(w2.primary_ring_name, ' & '::text ORDER BY rp."position") AS string_agg FROM reign_participants rp JOIN wrestlers w2 ON w2.id = rp.wrestler_id WHERE rp.reign_id = r.id), w.primary_ring_name) AS holder_display, ( SELECT array_agg(w2.primary_ring_name ORDER BY rp."position") AS array_agg FROM reign_participants rp JOIN wrestlers w2 ON w2.id = rp.wrestler_id WHERE rp.reign_id = r.id) AS participant_names, r.is_vacancy, r.sequence_order, r.reign_number, r.reign_number_for_wrestler, r.start_date, r.end_date, r.start_date_precision, r.end_date_precision, r.duration_days, r.won_in_city, r.won_in_state, r.won_in_country, r.source_url, r.notes FROM reigns r JOIN titles t ON t.id = r.title_id LEFT JOIN wrestlers w ON w.id = r.wrestler_id);--> statement-breakpoint
CREATE VIEW "public"."v_title_lineage" AS (SELECT t.id AS title_id, t.name AS title_name, r.sequence_order, r.reign_number, CASE WHEN r.is_vacancy THEN 'VACANT'::text ELSE COALESCE(r.team_name, ( SELECT string_agg(w2.primary_ring_name, ' & '::text ORDER BY rp."position") AS string_agg FROM reign_participants rp JOIN wrestlers w2 ON w2.id = rp.wrestler_id WHERE rp.reign_id = r.id), w.primary_ring_name) END AS holder, r.team_name, r.reign_number_for_wrestler, r.start_date, r.end_date, r.duration_days, r.won_in_city, r.won_in_state, r.won_in_country, r.is_vacancy FROM titles t JOIN reigns r ON r.title_id = t.id LEFT JOIN wrestlers w ON w.id = r.wrestler_id ORDER BY t.id, r.sequence_order);--> statement-breakpoint
CREATE VIEW "public"."v_wrestler_title_history" AS (SELECT w.id AS wrestler_id, w.primary_ring_name AS wrestler_name, t.id AS title_id, t.name AS title_name, r.team_name, r.reign_number, r.reign_number_for_wrestler, r.start_date, r.end_date, r.duration_days, r.won_in_city, r.won_in_state, r.won_in_country, 'singles'::text AS reign_role FROM wrestlers w JOIN reigns r ON r.wrestler_id = w.id AND r.is_vacancy = false JOIN titles t ON t.id = r.title_id UNION ALL SELECT w.id AS wrestler_id, w.primary_ring_name AS wrestler_name, t.id AS title_id, t.name AS title_name, r.team_name, r.reign_number, r.reign_number_for_wrestler, r.start_date, r.end_date, r.duration_days, r.won_in_city, r.won_in_state, r.won_in_country, 'tag-partner-'::text || rp."position" AS reign_role FROM wrestlers w JOIN reign_participants rp ON rp.wrestler_id = w.id JOIN reigns r ON r.id = rp.reign_id AND r.is_vacancy = false JOIN titles t ON t.id = r.title_id);