CREATE TABLE "wrestler_book_citations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wrestler_book_citations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"wrestler_id" integer NOT NULL,
	"book_id" integer NOT NULL,
	"page" text,
	"excerpt" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
ALTER TABLE "wrestlers" ADD COLUMN "height_inches" integer;--> statement-breakpoint
ALTER TABLE "wrestlers" ADD COLUMN "weight_lbs" integer;--> statement-breakpoint
ALTER TABLE "wrestlers" ADD COLUMN "bio" text;--> statement-breakpoint
ALTER TABLE "wrestler_book_citations" ADD CONSTRAINT "wrestler_book_citations_wrestler_id_fkey" FOREIGN KEY ("wrestler_id") REFERENCES "public"."wrestlers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wrestler_book_citations" ADD CONSTRAINT "wrestler_book_citations_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_wbc_wrestler" ON "wrestler_book_citations" USING btree ("wrestler_id");--> statement-breakpoint
CREATE INDEX "idx_wbc_book" ON "wrestler_book_citations" USING btree ("book_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_wbc_wrestler_book_page" ON "wrestler_book_citations" USING btree ("wrestler_id","book_id","page");