CREATE TABLE "mcp_audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mcp_audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"code_hash" text NOT NULL,
	"code_excerpt" text NOT NULL,
	"dry_run" boolean DEFAULT false NOT NULL,
	"duration_ms" integer,
	"result_status" text NOT NULL,
	"rpc_calls" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"error_message" text
);
--> statement-breakpoint
CREATE INDEX "idx_mcp_audit_log_created" ON "mcp_audit_log" USING btree ("created_at");
