-- Territory map schema: markets, and the two span tables that carry the
-- 1926-1996 research. Nothing here is per-year; per-year is a view.
--
-- Grain matches wrestler_territory_runs (start_year/start_month/end_year/
-- end_month) so every span in this database reads the same way.

CREATE TYPE "public"."market_tier" AS ENUM('Primary', 'Secondary', 'Tertiary');--> statement-breakpoint

-- A town, independent of who ran it or when. Chicago is one row that both the
-- AWA and the St. Louis office point at.
--
-- state is NOT NULL because Postgres treats NULLs as distinct, so a nullable
-- column in the uniqueness key would let duplicate cities through.
CREATE TABLE "markets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "markets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"state" text NOT NULL,
	"country" text DEFAULT 'US' NOT NULL,
	"lat" double precision,
	"lon" double precision,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint

-- A stretch during which a promotion held one identity and one footprint.
-- Detroit under Harry Light, then Barnett-Doyle from 1959, then the Sheik from
-- 1964 is three rows against one territory, instead of three territories.
--
-- to_year NULL means open-ended.
CREATE TABLE "territory_eras" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "territory_eras_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"territory_id" integer NOT NULL,
	"from_year" integer NOT NULL,
	"from_month" integer,
	"to_year" integer,
	"to_month" integer,
	"states" text[],
	"nwa_member" boolean,
	"promotion_name" text,
	"promoter" text,
	"confidence" "confidence_level" DEFAULT 'medium',
	"source_id" integer,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp with time zone,
	CONSTRAINT "territory_eras_year_check" CHECK (from_year BETWEEN 1880 AND 2100 AND (to_year IS NULL OR to_year BETWEEN 1880 AND 2100)),
	CONSTRAINT "territory_eras_order_check" CHECK (to_year IS NULL OR to_year >= from_year),
	CONSTRAINT "territory_eras_month_check" CHECK ((from_month IS NULL OR from_month BETWEEN 1 AND 12) AND (to_month IS NULL OR to_month BETWEEN 1 AND 12))
);
--> statement-breakpoint

-- Which towns a promotion ran, over what stretch, and how big each was to
-- them. This is the table the research fills.
--
-- A town dropped and picked back up is two rows. A tier change is two rows.
-- The same market under two territories in one year is how the map draws a
-- split dot over a town two offices both ran.
CREATE TABLE "territory_market_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "territory_market_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"territory_id" integer NOT NULL,
	"market_id" integer NOT NULL,
	"from_year" integer NOT NULL,
	"from_month" integer,
	"to_year" integer,
	"to_month" integer,
	"tier" "market_tier" DEFAULT 'Secondary',
	"confidence" "confidence_level" DEFAULT 'medium',
	"source_id" integer,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp with time zone,
	CONSTRAINT "territory_market_runs_year_check" CHECK (from_year BETWEEN 1880 AND 2100 AND (to_year IS NULL OR to_year BETWEEN 1880 AND 2100)),
	CONSTRAINT "territory_market_runs_order_check" CHECK (to_year IS NULL OR to_year >= from_year),
	CONSTRAINT "territory_market_runs_month_check" CHECK ((from_month IS NULL OR from_month BETWEEN 1 AND 12) AND (to_month IS NULL OR to_month BETWEEN 1 AND 12))
);
--> statement-breakpoint

-- Fill color for the map. Only the promotions actually drawn need one.
ALTER TABLE "territories" ADD COLUMN "map_color" text;--> statement-breakpoint

ALTER TABLE "territory_eras" ADD CONSTRAINT "territory_eras_fk_0" FOREIGN KEY ("territory_id") REFERENCES "public"."territories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "territory_eras" ADD CONSTRAINT "territory_eras_fk_1" FOREIGN KEY ("source_id") REFERENCES "public"."research_sources"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "territory_market_runs" ADD CONSTRAINT "territory_market_runs_fk_0" FOREIGN KEY ("territory_id") REFERENCES "public"."territories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "territory_market_runs" ADD CONSTRAINT "territory_market_runs_fk_1" FOREIGN KEY ("market_id") REFERENCES "public"."markets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "territory_market_runs" ADD CONSTRAINT "territory_market_runs_fk_2" FOREIGN KEY ("source_id") REFERENCES "public"."research_sources"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint

CREATE INDEX "idx_markets_country" ON "markets" USING btree ("country");--> statement-breakpoint
CREATE INDEX "idx_markets_state" ON "markets" USING btree ("state");--> statement-breakpoint
CREATE UNIQUE INDEX "markets_name_state_country_key" ON "markets" USING btree ("name","state","country");--> statement-breakpoint
CREATE INDEX "idx_territory_eras_territory" ON "territory_eras" USING btree ("territory_id");--> statement-breakpoint
CREATE INDEX "idx_territory_eras_span" ON "territory_eras" USING btree ("from_year","to_year");--> statement-breakpoint
CREATE UNIQUE INDEX "territory_eras_territory_from_key" ON "territory_eras" USING btree ("territory_id","from_year");--> statement-breakpoint
CREATE INDEX "idx_tmr_market" ON "territory_market_runs" USING btree ("market_id");--> statement-breakpoint
CREATE INDEX "idx_tmr_territory" ON "territory_market_runs" USING btree ("territory_id");--> statement-breakpoint
CREATE INDEX "idx_tmr_span" ON "territory_market_runs" USING btree ("from_year","to_year");--> statement-breakpoint
CREATE UNIQUE INDEX "territory_market_runs_key" ON "territory_market_runs" USING btree ("territory_id","market_id","from_year");--> statement-breakpoint

-- The per-year shape, derived. Nothing stores a year; this explodes the spans
-- on demand so you can ask what 1968 looked like.
CREATE VIEW "public"."v_territory_year_markets" AS (
SELECT
  r.territory_id,
  t.name AS territory_name,
  g.year,
  r.market_id,
  m.name AS market_name,
  m.state,
  m.country,
  m.lat,
  m.lon,
  r.tier,
  r.confidence
FROM territory_market_runs r
JOIN territories t ON t.id = r.territory_id
JOIN markets m ON m.id = r.market_id
CROSS JOIN LATERAL generate_series(
  r.from_year,
  COALESCE(r.to_year, EXTRACT(YEAR FROM CURRENT_DATE)::integer)
) AS g(year));
