-- Restores mcp_audit_log, which 0004 created but which had gone missing from the
-- long-lived local wrestling_bibliography database (the table, its identity
-- sequence, and its index were all absent). 0004 is already recorded in
-- drizzle.__drizzle_migrations, and the migrator only replays journal entries
-- newer than max(created_at), so 0004 can never run again. This forward
-- migration is the reproducible way back to the shape lib/db/schema/tables.ts
-- already declares.
--
-- IF NOT EXISTS keeps it a no-op wherever 0004 did take effect, such as the
-- test Testcontainer, which builds every database from 0000 forward.
CREATE TABLE IF NOT EXISTS "mcp_audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mcp_audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"code_hash" text NOT NULL,
	"code_excerpt" text NOT NULL,
	"dry_run" boolean DEFAULT false NOT NULL,
	"duration_ms" integer,
	"result_status" text NOT NULL,
	"rpc_calls" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"error_message" text
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_mcp_audit_log_created" ON "mcp_audit_log" USING btree ("created_at");
