-- Substack ingest: an archive of pro-wrestling-history newsletters, plus the
-- outbound links each post cites.
--
-- Three tables. A publication is a newsletter (one row per host). A post is one
-- article. Cited links do NOT get their own table -- they land in the existing
-- research_sources, so a URL a blogger cited and a URL curated by hand are the
-- same row, and substack_post_sources is only the join.

CREATE TABLE "substack_publications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "substack_publications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"host" text NOT NULL,
	"url" text NOT NULL,
	"author" text,
	"description" text,
	"language" text DEFAULT 'English',
	"focus" text,
	"active" boolean DEFAULT true NOT NULL,
	"first_post_at" timestamp with time zone,
	"last_post_at" timestamp with time zone,
	"last_fetched_at" timestamp with time zone,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp with time zone,
	CONSTRAINT "substack_publications_host_key" UNIQUE("host")
);
--> statement-breakpoint

-- body_html is the post as Substack serves it; body_text is the same content
-- flattened for reading and full-text search. raw keeps the whole API payload
-- so a parser change can be replayed without re-fetching the publication.
--
-- body_truncated marks a paywalled post where only the free teaser came back.
-- Those rows are still worth keeping -- the title, date, and teaser links are
-- real data -- but a search hit on one is not a search hit on the whole post.
CREATE TABLE "substack_posts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "substack_posts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"publication_id" integer NOT NULL,
	"substack_post_id" integer,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"subtitle" text,
	"author" text,
	"published_at" timestamp with time zone,
	"canonical_url" text NOT NULL,
	"post_type" text,
	"audience" text,
	"body_truncated" boolean DEFAULT false NOT NULL,
	"description" text,
	"cover_image_url" text,
	"podcast_url" text,
	"body_html" text,
	"body_text" text,
	"word_count" integer,
	"fetched_at" timestamp with time zone,
	"raw" jsonb,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp with time zone,
	CONSTRAINT "substack_posts_publication_id_slug_key" UNIQUE("publication_id","slug"),
	CONSTRAINT "substack_posts_publication_id_substack_post_id_key" UNIQUE("publication_id","substack_post_id")
);
--> statement-breakpoint

-- One row per distinct URL a post cites. occurrence_count collapses a link
-- repeated through an article; anchor_text and context keep the first mention's
-- wording, which is usually what identifies the source ("Meltzer's 1987 issue").
CREATE TABLE "substack_post_sources" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "substack_post_sources_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"post_id" integer NOT NULL,
	"source_id" integer NOT NULL,
	"anchor_text" text,
	"context" text,
	"link_kind" text,
	"first_position" integer,
	"occurrence_count" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "substack_post_sources_post_id_source_id_key" UNIQUE("post_id","source_id")
);
--> statement-breakpoint

ALTER TABLE "substack_posts" ADD CONSTRAINT "substack_posts_fk_0" FOREIGN KEY ("publication_id") REFERENCES "public"."substack_publications"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "substack_post_sources" ADD CONSTRAINT "substack_post_sources_fk_0" FOREIGN KEY ("post_id") REFERENCES "public"."substack_posts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "substack_post_sources" ADD CONSTRAINT "substack_post_sources_fk_1" FOREIGN KEY ("source_id") REFERENCES "public"."research_sources"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

CREATE INDEX "idx_substack_posts_publication_date" ON "substack_posts" USING btree ("publication_id","published_at");--> statement-breakpoint
CREATE INDEX "idx_substack_posts_published" ON "substack_posts" USING btree ("published_at");--> statement-breakpoint
CREATE INDEX "idx_substack_post_sources_source" ON "substack_post_sources" USING btree ("source_id");--> statement-breakpoint

-- Search across the corpus without a separate index pipeline. The regconfig is
-- a literal so the expression stays immutable and is therefore indexable.
CREATE INDEX "idx_substack_posts_fts" ON "substack_posts" USING gin (to_tsvector('english', coalesce("title", '') || ' ' || coalesce("subtitle", '') || ' ' || coalesce("body_text", '')));
