#!/usr/bin/env python3
"""
migrate_titles_reigns.py

Adds the championship-history schema to Postgres:

  titles            — one row per championship lineage
  title_aliases     — historic name changes (cagematch's "Names:" section)
  reigns            — one row per holder OR vacancy, chronological per title

Plus convenience views:

  v_current_champions        — current holder per title (most recent non-vacancy reign)
  v_reigns_full              — denormalized: reign + title name + wrestler name
  v_title_lineage            — chronological lineage per title (incl. vacancies)
  v_longest_reigns           — reigns sorted by duration_days
  v_wrestler_title_history   — per wrestler, all their reigns

Postgres only — see project README. SQLite is no longer the source of truth.
Idempotent: safe to re-run.

Run: python3 bibliography/migrate_titles_reigns.py
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import psycopg


def database_url() -> str:
    if url := os.environ.get("DATABASE_URL"):
        return url
    host = os.environ.get("PWBIB_PG_HOST", "localhost")
    port = os.environ.get("PWBIB_PG_PORT", "5432")
    db   = os.environ.get("PWBIB_PG_DB", "wrestling_bibliography")
    user = os.environ.get("PWBIB_PG_USER")
    auth = f"{user}@" if user else ""
    return f"postgresql://{auth}{host}:{port}/{db}"


DDL = r"""
-- =====================================================================
-- titles : one row per championship lineage
-- =====================================================================
CREATE TABLE IF NOT EXISTS titles (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    status          TEXT,                       -- active | inactive | retired | unified
    title_type      TEXT,                       -- singles | tag | trios | six-man | other
    weight_class    TEXT,                       -- heavyweight | junior | women | tv | etc.
    territory_id    INTEGER REFERENCES territories(id) ON DELETE SET NULL,
    promotion_name  TEXT,                       -- free-text fallback when no territory_id
    inception_date  TEXT,                       -- 'YYYY-MM-DD' / 'YYYY-MM' / 'YYYY'
    retired_date    TEXT,
    cagematch_id    TEXT UNIQUE,
    cagematch_url   TEXT GENERATED ALWAYS AS (
                        CASE WHEN cagematch_id IS NOT NULL AND cagematch_id <> ''
                             THEN 'https://www.cagematch.net/?id=5&nr=' || cagematch_id
                             ELSE NULL END
                    ) STORED,
    notes           TEXT,
    created_at      TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_titles_territory ON titles (territory_id);
CREATE INDEX IF NOT EXISTS idx_titles_status    ON titles (status);
CREATE INDEX IF NOT EXISTS idx_titles_cm        ON titles (cagematch_id);

-- =====================================================================
-- title_aliases : historic name changes
-- =====================================================================
CREATE TABLE IF NOT EXISTS title_aliases (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_id        INTEGER NOT NULL REFERENCES titles(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    effective_from  TEXT,
    effective_to    TEXT,
    notes           TEXT,
    created_at      TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (title_id, name, effective_from)
);

CREATE INDEX IF NOT EXISTS idx_title_aliases_title ON title_aliases (title_id);

-- =====================================================================
-- reigns : one row per holder OR vacancy, chronological per title
-- =====================================================================
CREATE TABLE IF NOT EXISTS reigns (
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_id                    INTEGER NOT NULL REFERENCES titles(id) ON DELETE CASCADE,
    wrestler_id                 INTEGER REFERENCES wrestlers(id) ON DELETE SET NULL,
    is_vacancy                  BOOLEAN NOT NULL DEFAULT FALSE,
    sequence_order              INTEGER NOT NULL,    -- 1..N chronological, including vacancies
    reign_number                INTEGER,             -- cagematch's #N; NULL for vacancies
    reign_number_for_wrestler   INTEGER,             -- e.g. Bruiser (13) -> 13
    start_date                  TEXT,                -- 'YYYY-MM-DD' / 'YYYY-MM' / 'YYYY' / NULL
    end_date                    TEXT,
    start_date_precision        TEXT,                -- day | month | year | unknown
    end_date_precision          TEXT,
    duration_days               INTEGER,             -- nullable when either endpoint imprecise
    won_in_city                 TEXT,
    won_in_state                TEXT,
    won_in_country              TEXT,
    source_url                  TEXT,
    notes                       TEXT,
    created_at                  TEXT DEFAULT CURRENT_TIMESTAMP,
    CHECK (is_vacancy = FALSE OR wrestler_id IS NULL),
    UNIQUE (title_id, sequence_order)
);

CREATE INDEX IF NOT EXISTS idx_reigns_title    ON reigns (title_id);
CREATE INDEX IF NOT EXISTS idx_reigns_wrestler ON reigns (wrestler_id);
CREATE INDEX IF NOT EXISTS idx_reigns_start    ON reigns (start_date);
CREATE INDEX IF NOT EXISTS idx_reigns_vacancy  ON reigns (is_vacancy);

-- =====================================================================
-- views
-- =====================================================================

-- Current champion: most recent non-vacancy reign per title.
CREATE OR REPLACE VIEW v_current_champions AS
SELECT DISTINCT ON (r.title_id)
    t.id              AS title_id,
    t.name            AS title_name,
    t.status          AS title_status,
    r.id              AS reign_id,
    r.wrestler_id,
    w.primary_ring_name AS wrestler_name,
    r.reign_number,
    r.reign_number_for_wrestler,
    r.start_date,
    r.end_date,
    r.duration_days,
    r.won_in_city,
    r.won_in_state,
    r.won_in_country
FROM titles t
LEFT JOIN reigns r ON r.title_id = t.id AND r.is_vacancy = FALSE
LEFT JOIN wrestlers w ON w.id = r.wrestler_id
ORDER BY r.title_id, r.sequence_order DESC;

-- Denormalized reign rows with title + wrestler names baked in.
CREATE OR REPLACE VIEW v_reigns_full AS
SELECT
    r.id                          AS reign_id,
    r.title_id,
    t.name                        AS title_name,
    t.cagematch_id                AS title_cagematch_id,
    r.wrestler_id,
    w.primary_ring_name           AS wrestler_name,
    w.cagematch_id                AS wrestler_cagematch_id,
    r.is_vacancy,
    r.sequence_order,
    r.reign_number,
    r.reign_number_for_wrestler,
    r.start_date,
    r.end_date,
    r.start_date_precision,
    r.end_date_precision,
    r.duration_days,
    r.won_in_city,
    r.won_in_state,
    r.won_in_country,
    r.source_url,
    r.notes
FROM reigns r
JOIN titles t ON t.id = r.title_id
LEFT JOIN wrestlers w ON w.id = r.wrestler_id;

-- Per-title lineage in chronological order (vacancies inline).
CREATE OR REPLACE VIEW v_title_lineage AS
SELECT
    t.id                          AS title_id,
    t.name                        AS title_name,
    r.sequence_order,
    r.reign_number,
    CASE WHEN r.is_vacancy THEN 'VACANT' ELSE w.primary_ring_name END AS holder,
    r.reign_number_for_wrestler,
    r.start_date,
    r.end_date,
    r.duration_days,
    r.won_in_city,
    r.won_in_state,
    r.won_in_country,
    r.is_vacancy
FROM titles t
JOIN reigns r ON r.title_id = t.id
LEFT JOIN wrestlers w ON w.id = r.wrestler_id
ORDER BY t.id, r.sequence_order;

-- Longest reigns (excluding vacancies, only fully-dated reigns).
CREATE OR REPLACE VIEW v_longest_reigns AS
SELECT
    r.id                          AS reign_id,
    t.name                        AS title_name,
    w.primary_ring_name           AS wrestler_name,
    r.reign_number,
    r.reign_number_for_wrestler,
    r.start_date,
    r.end_date,
    r.duration_days
FROM reigns r
JOIN titles t ON t.id = r.title_id
JOIN wrestlers w ON w.id = r.wrestler_id
WHERE r.is_vacancy = FALSE
  AND r.duration_days IS NOT NULL
ORDER BY r.duration_days DESC;

-- Title history per wrestler.
CREATE OR REPLACE VIEW v_wrestler_title_history AS
SELECT
    w.id                          AS wrestler_id,
    w.primary_ring_name           AS wrestler_name,
    t.id                          AS title_id,
    t.name                        AS title_name,
    r.reign_number,
    r.reign_number_for_wrestler,
    r.start_date,
    r.end_date,
    r.duration_days,
    r.won_in_city,
    r.won_in_state,
    r.won_in_country
FROM wrestlers w
JOIN reigns r ON r.wrestler_id = w.id AND r.is_vacancy = FALSE
JOIN titles t ON t.id = r.title_id
ORDER BY w.primary_ring_name, t.name, r.sequence_order;
"""


def main() -> int:
    url = database_url()
    print(f"Connecting: {url}")
    with psycopg.connect(url) as conn:
        with conn.cursor() as cur:
            cur.execute(DDL)
        conn.commit()

        # Sanity check
        with conn.cursor() as cur:
            cur.execute("""
                SELECT table_name
                  FROM information_schema.tables
                 WHERE table_schema = 'public'
                   AND table_name IN ('titles','title_aliases','reigns')
                 ORDER BY table_name
            """)
            tables = [r[0] for r in cur.fetchall()]
            cur.execute("""
                SELECT table_name
                  FROM information_schema.views
                 WHERE table_schema = 'public'
                   AND table_name LIKE 'v_%'
                   AND table_name IN (
                       'v_current_champions','v_reigns_full','v_title_lineage',
                       'v_longest_reigns','v_wrestler_title_history'
                   )
                 ORDER BY table_name
            """)
            views = [r[0] for r in cur.fetchall()]

    print("Tables:", tables)
    print("Views: ", views)
    print("Migration complete.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
