#!/usr/bin/env python3
"""
Migrate the wrestling bibliography SQLite database to local PostgreSQL.

The script produces a PostgreSQL SQL import file from the SQLite source, then
optionally applies it with psql. It is intentionally dependency-free: sqlite3,
subprocess, and the local PostgreSQL client are enough.
"""
from __future__ import annotations

import argparse
import os
import re
import sqlite3
import subprocess
import sys
from pathlib import Path
from typing import Iterable


DEFAULT_SQLITE_DB = Path(__file__).with_name("wrestling_bibliography.db")
DEFAULT_OUTPUT_SQL = Path(__file__).with_name("wrestling_bibliography_postgres.sql")
DEFAULT_PG_DB = "wrestling_bibliography"


def qident(name: str) -> str:
    if re.fullmatch(r"[a-z_][a-z0-9_]*", name):
        return name
    return '"' + name.replace('"', '""') + '"'


def sqlite_table_counts(sqlite_path: Path) -> dict[str, int]:
    conn = sqlite3.connect(sqlite_path)
    try:
        tables = [
            row[0]
            for row in conn.execute(
                """
                SELECT name
                  FROM sqlite_master
                 WHERE type = 'table'
                   AND name NOT LIKE 'sqlite_%'
                 ORDER BY name
                """
            )
        ]
        return {table: conn.execute(f"SELECT COUNT(*) FROM {qident(table)}").fetchone()[0] for table in tables}
    finally:
        conn.close()


def validate_sqlite_source(sqlite_path: Path) -> None:
    if not sqlite_path.exists():
        raise SystemExit(f"SQLite DB not found: {sqlite_path}")
    if sqlite_path.stat().st_size == 0:
        raise SystemExit(f"SQLite DB is empty: {sqlite_path}")
    conn = sqlite3.connect(sqlite_path)
    try:
        result = conn.execute("PRAGMA integrity_check").fetchone()[0]
        if result != "ok":
            raise SystemExit(f"SQLite integrity_check failed: {result}")
    finally:
        conn.close()


def pg_type(sqlite_type: str) -> str:
    t = (sqlite_type or "").upper()
    if "INT" in t:
        return "INTEGER"
    if "CHAR" in t or "CLOB" in t or "TEXT" in t:
        return "TEXT"
    if "REAL" in t or "FLOA" in t or "DOUB" in t:
        return "DOUBLE PRECISION"
    if "BLOB" in t:
        return "BYTEA"
    return "TEXT"


def pg_default(default: object) -> str | None:
    if default is None:
        return None
    value = str(default)
    if value.upper() == "CURRENT_TIMESTAMP":
        return "CURRENT_TIMESTAMP"
    return value


def generated_column_sql(table: str, column: str) -> str | None:
    if column == "cagematch_url" and table == "territories":
        return (
            "TEXT GENERATED ALWAYS AS "
            "(CASE WHEN cagematch_id IS NOT NULL AND cagematch_id <> '' "
            "THEN 'https://www.cagematch.net/?id=8&nr=' || cagematch_id ELSE NULL END) STORED"
        )
    if column == "cagematch_url" and table == "wrestlers":
        return (
            "TEXT GENERATED ALWAYS AS "
            "(CASE WHEN cagematch_id IS NOT NULL AND cagematch_id <> '' "
            "THEN 'https://www.cagematch.net/?id=2&nr=' || cagematch_id ELSE NULL END) STORED"
        )
    return None


def table_columns(conn: sqlite3.Connection, table: str) -> list[sqlite3.Row]:
    return conn.execute(f"PRAGMA table_xinfo({qident(table)})").fetchall()


def visible_columns(conn: sqlite3.Connection, table: str) -> list[str]:
    return [row["name"] for row in table_columns(conn, table) if row["hidden"] == 0]


def render_create_table(conn: sqlite3.Connection, table: str) -> str:
    columns = []
    pk_rows = [row for row in table_columns(conn, table) if row["pk"]]
    single_integer_pk = (
        len(pk_rows) == 1
        and pk_rows[0]["pk"] == 1
        and (pk_rows[0]["type"] or "").upper() == "INTEGER"
    )
    for row in table_columns(conn, table):
        name = row["name"]
        generated = generated_column_sql(table, name) if row["hidden"] else None
        if generated:
            columns.append(f"    {qident(name)} {generated}")
            continue
        if row["hidden"]:
            continue

        is_integer_pk = single_integer_pk and row["pk"] == 1
        if is_integer_pk:
            line = f"    {qident(name)} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        else:
            line = f"    {qident(name)} {pg_type(row['type'])}"
            default = pg_default(row["dflt_value"])
            if default is not None:
                line += f" DEFAULT {default}"
            if row["notnull"]:
                line += " NOT NULL"
        columns.append(line)

    composite_pk = [row["name"] for row in sorted(pk_rows, key=lambda r: r["pk"])]
    if len(composite_pk) > 1:
        columns.append("    PRIMARY KEY (" + ", ".join(qident(c) for c in composite_pk) + ")")
    return f"CREATE TABLE {qident(table)} (\n" + ",\n".join(columns) + "\n);\n"


def copy_value(value: object) -> str:
    if value is None:
        return r"\N"
    text = str(value)
    return (
        text.replace("\\", "\\\\")
        .replace("\t", r"\t")
        .replace("\n", r"\n")
        .replace("\r", r"\r")
    )


def render_copy_data(conn: sqlite3.Connection, table: str) -> str:
    cols = visible_columns(conn, table)
    out = [f"COPY {qident(table)} ({', '.join(qident(c) for c in cols)}) FROM stdin;"]
    cur = conn.execute(f"SELECT {', '.join(qident(c) for c in cols)} FROM {qident(table)}")
    for row in cur:
        out.append("\t".join(copy_value(value) for value in row))
    out.append(r"\.")
    return "\n".join(out) + "\n"


def render_indexes(conn: sqlite3.Connection, table: str) -> Iterable[str]:
    for idx in conn.execute(f"PRAGMA index_list({qident(table)})"):
        name = idx["name"]
        if name.startswith("sqlite_autoindex_"):
            name = f"{table}_{'_'.join(index_columns(conn, idx['name']))}_key"
        unique = "UNIQUE " if idx["unique"] else ""
        cols = index_columns(conn, idx["name"])
        if not cols:
            continue
        yield (
            f"CREATE {unique}INDEX IF NOT EXISTS {qident(name)} "
            f"ON {qident(table)} ({', '.join(qident(c) for c in cols)});"
        )


def index_columns(conn: sqlite3.Connection, index_name: str) -> list[str]:
    return [row["name"] for row in conn.execute(f"PRAGMA index_info({qident(index_name)})")]


def render_foreign_keys(conn: sqlite3.Connection, table: str) -> Iterable[str]:
    fks: dict[int, list[sqlite3.Row]] = {}
    for row in conn.execute(f"PRAGMA foreign_key_list({qident(table)})"):
        fks.setdefault(row["id"], []).append(row)
    for fk_id, rows in fks.items():
        rows = sorted(rows, key=lambda r: r["seq"])
        from_cols = ", ".join(qident(r["from"]) for r in rows)
        to_cols = ", ".join(qident(r["to"]) for r in rows)
        target = rows[0]["table"]
        clause = (
            f"ALTER TABLE {qident(table)} ADD CONSTRAINT {qident(f'{table}_fk_{fk_id}')} "
            f"FOREIGN KEY ({from_cols}) REFERENCES {qident(target)} ({to_cols})"
        )
        if rows[0]["on_delete"] and rows[0]["on_delete"].upper() != "NO ACTION":
            clause += f" ON DELETE {rows[0]['on_delete'].upper()}"
        yield clause + ";"


def translate_view_sql(sql: str) -> str:
    return sql.replace("GROUP_CONCAT(COALESCE(w.primary_ring_name, ics.subject_name), ', ')", "string_agg(COALESCE(w.primary_ring_name, ics.subject_name), ', ')")


def render_sequences(conn: sqlite3.Connection, table: str) -> Iterable[str]:
    pk_rows = [row for row in table_columns(conn, table) if row["pk"]]
    if len(pk_rows) != 1:
        return
    for row in table_columns(conn, table):
        if row["pk"] == 1 and (row["type"] or "").upper() == "INTEGER":
            value = conn.execute(f"SELECT MAX({qident(row['name'])}) FROM {qident(table)}").fetchone()
            break
    else:
        return
    max_id = value[0] if value and value[0] is not None else 1
    is_called = "true" if value and value[0] is not None else "false"
    yield f"SELECT setval(pg_get_serial_sequence('{table}', '{row['name']}'), {max_id}, {is_called});"


def render_postgres_sql(sqlite_path: Path) -> str:
    validate_sqlite_source(sqlite_path)
    conn = sqlite3.connect(sqlite_path)
    conn.row_factory = sqlite3.Row
    try:
        tables = [
            row["name"]
            for row in conn.execute(
                """
                SELECT name
                  FROM sqlite_master
                 WHERE type = 'table'
                   AND name NOT LIKE 'sqlite_%'
                 ORDER BY name
                """
            )
        ]
        views = conn.execute(
            "SELECT name, sql FROM sqlite_master WHERE type = 'view' ORDER BY name"
        ).fetchall()

        out = [
            "-- Generated by bibliography/migrate_to_postgres.py",
            "BEGIN;",
            "SET client_encoding = 'UTF8';",
            "DROP SCHEMA IF EXISTS public CASCADE;",
            "CREATE SCHEMA public;",
            "",
        ]
        for table in tables:
            out.append(render_create_table(conn, table))
        for table in tables:
            out.append(render_copy_data(conn, table))
        for table in tables:
            out.extend(render_indexes(conn, table))
        for table in tables:
            out.extend(render_foreign_keys(conn, table))
        for table in tables:
            out.extend(render_sequences(conn, table))
        for view in views:
            out.append(translate_view_sql(view["sql"]) + ";")
        out.append("COMMIT;")
        return "\n".join(out) + "\n"
    finally:
        conn.close()


def run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True)


def database_exists(dbname: str, host: str | None = None) -> bool:
    cmd = ["psql"]
    if host:
        cmd += ["-h", host]
    cmd += ["-d", "postgres", "-tAc", "SELECT 1 FROM pg_database WHERE datname = '" + dbname.replace("'", "''") + "'"]
    result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    return result.stdout.strip() == "1"


def ensure_database(dbname: str, host: str | None = None) -> None:
    if database_exists(dbname, host):
        return
    cmd = ["createdb"]
    if host:
        cmd += ["-h", host]
    cmd.append(dbname)
    run(cmd)


def apply_sql(sql_path: Path, dbname: str, host: str | None = None) -> None:
    cmd = ["psql"]
    if host:
        cmd += ["-h", host]
    cmd += ["-v", "ON_ERROR_STOP=1", "-d", dbname, "-f", str(sql_path)]
    run(cmd)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sqlite-db", type=Path, default=DEFAULT_SQLITE_DB)
    parser.add_argument("--output-sql", type=Path, default=DEFAULT_OUTPUT_SQL)
    parser.add_argument("--pg-db", default=os.environ.get("PWBIB_PG_DB", DEFAULT_PG_DB))
    parser.add_argument("--pg-host", default=os.environ.get("PWBIB_PG_HOST", "localhost"))
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    sql = render_postgres_sql(args.sqlite_db)
    args.output_sql.write_text(sql)
    print(f"Wrote {args.output_sql}")
    print("SQLite row counts:")
    for table, count in sqlite_table_counts(args.sqlite_db).items():
        print(f"  {table}: {count}")

    if args.apply:
        ensure_database(args.pg_db, args.pg_host)
        apply_sql(args.output_sql, args.pg_db, args.pg_host)
        print(f"Applied to PostgreSQL database: {args.pg_db}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
