#!/usr/bin/env python3
"""
migrate_titles_tag_support.py

Extends the titles/reigns schema to handle tag teams (and beyond):

  - reigns.team_name              new column (e.g. "The Motor City Hitmen")
  - reign_participants            new table linking reigns to multiple wrestlers

For singles reigns the existing pattern still applies:
  reigns.wrestler_id is populated, reign_participants is empty.

For tag (or trios) reigns:
  reigns.wrestler_id is NULL, reigns.team_name is optional, and
  reign_participants holds one row per partner.

All views are recreated to render a unified holder display:
  team_name  →  participants joined " & "  →  single wrestler

Postgres only. Idempotent. Safe to run after migrate_titles_reigns.py.
"""
from __future__ import annotations

import os
import sys

import psycopg


def database_url() -> str:
    if url := os.environ.get("DATABASE_URL"):
        return url
    host = os.environ.get("PWBIB_PG_HOST", "localhost")
    port = os.environ.get("PWBIB_PG_PORT", "5432")
    db   = os.environ.get("PWBIB_PG_DB", "wrestling_bibliography")
    user = os.environ.get("PWBIB_PG_USER")
    auth = f"{user}@" if user else ""
    return f"postgresql://{auth}{host}:{port}/{db}"


DDL = r"""
ALTER TABLE reigns
    ADD COLUMN IF NOT EXISTS team_name TEXT;

CREATE TABLE IF NOT EXISTS reign_participants (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reign_id        INTEGER NOT NULL REFERENCES reigns(id) ON DELETE CASCADE,
    wrestler_id     INTEGER NOT NULL REFERENCES wrestlers(id) ON DELETE CASCADE,
    position        INTEGER NOT NULL,    -- 1, 2 (partner order)
    ring_name_used  TEXT,                -- the ring name used during this reign
    UNIQUE (reign_id, wrestler_id),
    UNIQUE (reign_id, position)
);

CREATE INDEX IF NOT EXISTS idx_reign_participants_reign
    ON reign_participants (reign_id);
CREATE INDEX IF NOT EXISTS idx_reign_participants_wrestler
    ON reign_participants (wrestler_id);

-- =====================================================================
-- views (drop + recreate; column order changes, so CREATE OR REPLACE
-- isn't enough — Postgres won't reorder columns under that statement)
-- =====================================================================
DROP VIEW IF EXISTS v_current_champions       CASCADE;
DROP VIEW IF EXISTS v_reigns_full             CASCADE;
DROP VIEW IF EXISTS v_title_lineage           CASCADE;
DROP VIEW IF EXISTS v_longest_reigns          CASCADE;
DROP VIEW IF EXISTS v_wrestler_title_history  CASCADE;

CREATE VIEW v_reigns_full AS
SELECT
    r.id                          AS reign_id,
    r.title_id,
    t.name                        AS title_name,
    t.cagematch_id                AS title_cagematch_id,
    r.wrestler_id,
    w.primary_ring_name           AS wrestler_name,
    w.cagematch_id                AS wrestler_cagematch_id,
    r.team_name,
    COALESCE(
        CASE WHEN r.is_vacancy THEN 'VACANT' END,
        r.team_name,
        (SELECT string_agg(w2.primary_ring_name, ' & ' ORDER BY rp.position)
           FROM reign_participants rp
           JOIN wrestlers w2 ON w2.id = rp.wrestler_id
          WHERE rp.reign_id = r.id),
        w.primary_ring_name
    )                             AS holder_display,
    (SELECT array_agg(w2.primary_ring_name ORDER BY rp.position)
       FROM reign_participants rp
       JOIN wrestlers w2 ON w2.id = rp.wrestler_id
      WHERE rp.reign_id = r.id)   AS participant_names,
    r.is_vacancy,
    r.sequence_order,
    r.reign_number,
    r.reign_number_for_wrestler,
    r.start_date,
    r.end_date,
    r.start_date_precision,
    r.end_date_precision,
    r.duration_days,
    r.won_in_city,
    r.won_in_state,
    r.won_in_country,
    r.source_url,
    r.notes
FROM reigns r
JOIN titles t ON t.id = r.title_id
LEFT JOIN wrestlers w ON w.id = r.wrestler_id;


CREATE VIEW v_current_champions AS
SELECT DISTINCT ON (r.title_id)
    t.id              AS title_id,
    t.name            AS title_name,
    t.status          AS title_status,
    r.id              AS reign_id,
    r.wrestler_id,
    w.primary_ring_name AS wrestler_name,
    r.team_name,
    COALESCE(
        r.team_name,
        (SELECT string_agg(w2.primary_ring_name, ' & ' ORDER BY rp.position)
           FROM reign_participants rp
           JOIN wrestlers w2 ON w2.id = rp.wrestler_id
          WHERE rp.reign_id = r.id),
        w.primary_ring_name
    )                 AS holder_display,
    r.reign_number,
    r.reign_number_for_wrestler,
    r.start_date,
    r.end_date,
    r.duration_days,
    r.won_in_city,
    r.won_in_state,
    r.won_in_country
FROM titles t
LEFT JOIN reigns r ON r.title_id = t.id AND r.is_vacancy = FALSE
LEFT JOIN wrestlers w ON w.id = r.wrestler_id
ORDER BY r.title_id, r.sequence_order DESC;


CREATE VIEW v_title_lineage AS
SELECT
    t.id                          AS title_id,
    t.name                        AS title_name,
    r.sequence_order,
    r.reign_number,
    CASE
        WHEN r.is_vacancy THEN 'VACANT'
        ELSE COALESCE(
            r.team_name,
            (SELECT string_agg(w2.primary_ring_name, ' & ' ORDER BY rp.position)
               FROM reign_participants rp
               JOIN wrestlers w2 ON w2.id = rp.wrestler_id
              WHERE rp.reign_id = r.id),
            w.primary_ring_name
        )
    END                           AS holder,
    r.team_name,
    r.reign_number_for_wrestler,
    r.start_date,
    r.end_date,
    r.duration_days,
    r.won_in_city,
    r.won_in_state,
    r.won_in_country,
    r.is_vacancy
FROM titles t
JOIN reigns r ON r.title_id = t.id
LEFT JOIN wrestlers w ON w.id = r.wrestler_id
ORDER BY t.id, r.sequence_order;


CREATE VIEW v_longest_reigns AS
SELECT
    r.id                          AS reign_id,
    t.name                        AS title_name,
    COALESCE(
        r.team_name,
        (SELECT string_agg(w2.primary_ring_name, ' & ' ORDER BY rp.position)
           FROM reign_participants rp
           JOIN wrestlers w2 ON w2.id = rp.wrestler_id
          WHERE rp.reign_id = r.id),
        w.primary_ring_name
    )                             AS holder_display,
    r.team_name,
    r.reign_number,
    r.reign_number_for_wrestler,
    r.start_date,
    r.end_date,
    r.duration_days
FROM reigns r
JOIN titles t ON t.id = r.title_id
LEFT JOIN wrestlers w ON w.id = r.wrestler_id
WHERE r.is_vacancy = FALSE
  AND r.duration_days IS NOT NULL
ORDER BY r.duration_days DESC;


-- Per-wrestler title history. For tag titles this surfaces every reign
-- the wrestler participated in, via reign_participants.
CREATE VIEW v_wrestler_title_history AS
SELECT
    w.id                          AS wrestler_id,
    w.primary_ring_name           AS wrestler_name,
    t.id                          AS title_id,
    t.name                        AS title_name,
    r.team_name,
    r.reign_number,
    r.reign_number_for_wrestler,
    r.start_date,
    r.end_date,
    r.duration_days,
    r.won_in_city,
    r.won_in_state,
    r.won_in_country,
    'singles' AS reign_role
FROM wrestlers w
JOIN reigns r ON r.wrestler_id = w.id AND r.is_vacancy = FALSE
JOIN titles t ON t.id = r.title_id

UNION ALL

SELECT
    w.id                          AS wrestler_id,
    w.primary_ring_name           AS wrestler_name,
    t.id                          AS title_id,
    t.name                        AS title_name,
    r.team_name,
    r.reign_number,
    r.reign_number_for_wrestler,
    r.start_date,
    r.end_date,
    r.duration_days,
    r.won_in_city,
    r.won_in_state,
    r.won_in_country,
    'tag-partner-' || rp.position AS reign_role
FROM wrestlers w
JOIN reign_participants rp ON rp.wrestler_id = w.id
JOIN reigns r ON r.id = rp.reign_id AND r.is_vacancy = FALSE
JOIN titles t ON t.id = r.title_id;
"""


def main() -> int:
    url = database_url()
    print(f"Connecting: {url}")
    with psycopg.connect(url) as conn:
        with conn.cursor() as cur:
            cur.execute(DDL)
        conn.commit()

        with conn.cursor() as cur:
            cur.execute("""
                SELECT column_name FROM information_schema.columns
                 WHERE table_schema = 'public'
                   AND table_name = 'reigns'
                   AND column_name = 'team_name'
            """)
            has_team = cur.fetchone() is not None

            cur.execute("""
                SELECT 1 FROM information_schema.tables
                 WHERE table_schema = 'public' AND table_name = 'reign_participants'
            """)
            has_participants = cur.fetchone() is not None

    print(f"reigns.team_name present:    {has_team}")
    print(f"reign_participants present:  {has_participants}")
    print("Tag-team migration complete.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
